# -*- coding: utf-8 -*-
"""Assignment1_SitiNurRafidah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNYV4YfgP0i7X-Wr80R1eOPfCcs_l1he
"""

'''
Temperature Converter

Write a Python program to convert temperatures to and from Celsius and Fahrenheit.

[ Formula : c/5 = f-32/9 [ where c = temperature in celsius and f = temperature in fahrenheit ]

Expected Output :

60°C is 140 in Fahrenheit
45°F is 7 in Celsius
'''

c = 60
f = 45


print(f'{c}°c is {((c/5)*9)+32} in Fahrenheit')
print(f'{f}°f is {round(((f-32)/9)*5)} in Celsius')

'''
Count Even and Odd Numbers

Write a Python program to count the number of even and odd numbers in a series of numbers

Sample numbers : numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

Expected Output :

Number of even numbers : 5
Number of odd numbers : 4
'''

numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)
sq_nums = [ i%2 for i in numbers]
print(f'number of even numbers: {sq_nums.count(0)}')
print(f'number of odd numbers: {sq_nums.count(1)}')

'''
Fibonacci Series Between 0 and 50

Write a Python program to get the Fibonacci series between 0 and 50.

Note : The Fibonacci Sequence is the series of numbers :

0, 1, 1, 2, 3, 5, 8, 13, 21, ....
Every next number is found by adding up the two numbers before it.

Expected Output : 1 1 2 3 5 8 13 21 34
'''

fibonacci = [0, 1, 1, 2, 3, 5, 8, 13, 21]
i = len(fibonacci)
while True:
    next_num = fibonacci[i - 1] + fibonacci[i - 2]
    if next_num >= 50:
        break
    fibonacci.append(next_num)
    i += 1

print(fibonacci[1:])

'''
FizzBuzz Variation

Write a Python program that iterates the integers from 1 to 50. For multiples of three print "Fizz" instead of the number and for multiples of five print "Buzz". For numbers that are multiples of three and five, print "FizzBuzz".

Sample Output :

fizzbuzz
1
2
fizz
4
buzz
'''

for i in range(1, 51):

    if i % 3 == 0 and i % 5 == 0:
        print("fizzbuzz")
    elif i % 3 == 0:
        print("fizz")
    elif i % 5 == 0:
        print("buzz")
    else:
        print(i)

'''
Password Validity Checker

Write a Python program to check the validity of passwords input by users.

Validation :

At least 1 letter between [a-z] and 1 letter between [A-Z].
At least 1 number between [0-9].
At least 1 character from [$#@].
Minimum length 6 characters.
Maximum length 16 characters.
'''

class PasswordValidator:
    def __init__(self, password):
        self.password = password
        self.special_chars = "$#@"

    def is_valid_length(self):
        return 6 <= len(self.password) <= 16

    def has_lowercase(self):
        return any(c.islower() for c in self.password)

    def has_uppercase(self):
        return any(c.isupper() for c in self.password)

    def has_digit(self):
        return any(c.isdigit() for c in self.password)

    def has_special(self):
        return any(c in self.special_chars for c in self.password)

    def is_valid(self):
        return all([
            self.is_valid_length(),
            self.has_lowercase(),
            self.has_uppercase(),
            self.has_digit(),
            self.has_special()
        ])

password = input("Enter password: ")
validator = PasswordValidator(password)
print("Valid Password" if validator.is_valid() else "Invalid Password")

'''
Dog Age in Dog Years

Write a Python program to calculate a dog's age in dog years.

Note: For the first two years, a dog year is equal to 10.5 human years. After that, each dog year equals 4 human years.

Expected Output:

Input a dog's age in human years: 15
The dog's age in dog's years is 73
'''

dog_years = lambda h: h*10.5 if h <= 2 else 21 + (h - 2)*4
age = float(input("Input a dog's age in human years: "))
print(f"The dog's age in dog's years is {int(dog_years(age))}")

'''
Astrological Sign Finder

Write a Python program to display the astrological sign for a given date of birth.

Expected Output:

Input birthday: 15
Input month of birth (e.g. march, july etc): may
Your Astrological sign is : Taurus
'''

def get_zodiac_sign(day, month):
    month = month.lower()
    if (month == 'december' and day >= 22) or (month == 'january' and day <= 19):
        return 'Capricorn'
    elif (month == 'january' and day >= 20) or (month == 'february' and day <= 18):
        return 'Aquarius'
    elif (month == 'february' and day >= 19) or (month == 'march' and day <= 20):
        return 'Pisces'
    elif (month == 'march' and day >= 21) or (month == 'april' and day <= 19):
        return 'Aries'
    elif (month == 'april' and day >= 20) or (month == 'may' and day <= 20):
        return 'Taurus'
    elif (month == 'may' and day >= 21) or (month == 'june' and day <= 20):
        return 'Gemini'
    elif (month == 'june' and day >= 21) or (month == 'july' and day <= 22):
        return 'Cancer'
    elif (month == 'july' and day >= 23) or (month == 'august' and day <= 22):
        return 'Leo'
    elif (month == 'august' and day >= 23) or (month == 'september' and day <= 22):
        return 'Virgo'
    elif (month == 'september' and day >= 23) or (month == 'october' and day <= 22):
        return 'Libra'
    elif (month == 'october' and day >= 23) or (month == 'november' and day <= 21):
        return 'Scorpio'
    elif (month == 'november' and day >= 22) or (month == 'december' and day <= 21):
        return 'Sagittarius'
    else:
        return 'Invalid input'
day = int(input("Input birthday: "))
month = input("Input month of birth (e.g. march, july etc): ")
print("Your Astrological sign is :", get_zodiac_sign(day, month))

'''
Chinese Zodiac Sign

Write a Python program to display the sign of the Chinese Zodiac for the given year in which you were born.

Expected Output:

Input your birth year: 1973
Your Zodiac sign : Ox
'''

def chinese_zodiac(year):

    zodiac_signs = ["Rat", "Ox", "Tiger", "Rabbit", "Dragon", "Snake",
                    "Horse", "Goat", "Monkey", "Rooster", "Dog", "Pig"]

    index = (year - 1900) % 12
    return zodiac_signs[index]

year = int(input("Input your birth year: "))

print(f"Your Zodiac sign: {chinese_zodiac(year)}")