# -*- coding: utf-8 -*-
"""Data_Structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/191t7gXmguEqSbjEw2YjqtZnXcHKKT4Eb
"""

# DAY5
# What Are Data Structures?
# Data structures are ways of organizing and storing data so that they
# can be accessed and modified efficiently.

# Why Should You, as a Developer, Learn Data Structures?
# The right data structure makes your code faster and more efficient.
# Most coding interviews and real-world challenges require solid data structure knowledge.
# Helps you organize code better and avoid messy or repeated logic.

# Python provides several built-in data structures
# List
# Tuple
# Set
# Dictionaries

# List In Python
# List is a collection of data values [ data structure ]
# List is denoted by using [] square brackets / list()
# List is Mutable In Nature [changeable , modifiable , delete]
# List allows us to have duplicate elements
# List allows us to have diff diff data types

# Create a list
list1 = [1,2,3,4,5,6,7,8,9,10]
print(type(list1))

list2 = list([1,2,3])
print(type(list2))

# Empty List
list3 = []
print(type(list3))

mylist = [10,20,30,40,50,60,70]
# 10  20  30   40   50   60   70
# 0   1    2    3    4   5     6
# -7  -6   -5   -4   -3  -2    -1
# Indexing and Slicing
print(mylist)
print(mylist[0])
print(mylist[5])
print(mylist[1:6])
print(mylist[1:6:2])
print(mylist[-1])

# using for loop
mylist =[10,20,30,40,50,60,70]
for i in mylist:
  if i%3==0:
    print(i)

# len() is built-in function that helps us to count the no. of elements
mylist =[10,20,30,40,50,60,70]
print(len(mylist))

mylist =[10,20,30,40,50,60,70]
for i in range(len(mylist)):           # range(7) for i in 0 1 2 3 4 5 6
  print(f'Index{i} : {mylist[i]}')     #                 Index {0} mylist[0]

# enumerate()
# built-in function which will show you indexNumber and the value

for i in enumerate(mylist):
  print(i)

for i,v in enumerate(mylist):
  print(f'Index {i} : {v}')

# List is mutable in nature
mylist = [10,20,30,40,50,50,50,50]
print(mylist)
mylist[4] = 1
print(mylist)

# List Built-In Function
help(list)
help(str)

mylist = [10,20,30,40,60,70,80,90,100]
print('Original List :',mylist)

# a.) append(value)
# used to add a new element at the END of the List
mylist.append(110)
print('After Append :',mylist)

# b.) insert(indexNumber,value)
# used to add a new element at any Specific Position
mylist.insert(6,1000)
print('After Insert :',mylist)

# c.) pop(indexNumber)
# used to delete an element from the specified index number from the list
mylist.pop(2)
print('After Pop :',mylist)

# d.) pop()
# if no argument is provided, it will delete the last element
mylist.pop()
print('After Pop :',mylist)

# e.) remove(value)
mylist.remove(70)
print('After Remove :',mylist)

# list = [10,20,30,40,10,10,10,50,60,70,10,80,10]
# list.remove(10) ? which 10 will it remove
# it will the first occurence of 10
# [20,30,40,10,10,10,50,60,70,10,80,10]
# while 10 in list:
#    list.remove(10)

# f.) reverse()
mylist.reverse()                   # print(mylist[::-1]) -> list slicing, reverse the list
print('After Reverse :',mylist)    # The full slicing syntax is [start:stop:step] -> leave start, stop blank mean incl whole list

# g.) clear()
# it is used to delete all the element from List
mylist.clear()
print('After Clear :',mylist)

# h.) del keyword -> will delete the entire of 'mylist'
del mylist

# i.) sort()
# work for int,float,string, and any data type
mylist = [7,8,1,3,6,9,5,2,4,10]
print(mylist)
mylist.sort()                     # sort in ascending order
print('After Sort :',mylist)

mylist = [7,8,1,3,6,9,5,2,4,10]
print(mylist)
mylist.sort(reverse=True)                     # sort in descending order
print('After Sort :',mylist)



fruits = ["cherry","apple","grape","durian","banana"]
fruits.sort()
print(fruits)

# USE WHILE LOOP WHEN NUMBER OF ITERATIONS ARE NOT FIXED
faculty_marks = []
howManySubjects = int(input('Enter How Many Subjects Marks You Wish To Insert : '))
i = 1
while i<=howManySubjects:
  marks = int(input(f'Enter Marks For Subject {i} : '))
  faculty_marks.append(marks)
  i += 1

print(faculty_marks)

# Tuple In Python
# Tuple is a collection of data values [ data structure ]
# Tuple is denoted by using () parenthesis / tuple()
# Tuple is Immutable In Nature
# Tuple allows us to have duplicate elements
# Tuple allows us to have diff diff data types

# Create a tuple
tuple1 = (1,2,3,4,5,6,7,8,9,10)
print(type(tuple1))

tuple2 = tuple((1,2,3))
print(type(tuple2))

tuple3 = ()
print(type(tuple3))

# determine the data type of following variable
myvar = 'Python' , 31 , 89.21 , True
print(type(myvar))

# how to define tuple having one element
var1 = (45,)
print(type(var1))
print(var1)

# Tuple is Immutable
mytuple = (10,20,30,40,50,60,70)
print(mytuple)
mytuple[3] = 400
print(mytuple)

# this error happened because tuple can't be mutable
# only way is just revised from the ori list

# function using tuple - where you dont want the information to get updated
# passportNo. ()
# personal iden no. ()

# len()
mytuple = (10,20,30,40,50,60,70,10,10,20,10,10,30,30)
print(len(mytuple))
# count(value) it is used to count the occurence of specified value
print(mytuple.count(10))
# index(value) it will return the index no. of specified value
print('Index No. Of 70 is',mytuple.index(70))

numbers = (7,8,1,3,6,9,5,2,4,10)
print(sorted(numbers))
# result will be in index

numbers = (7,8,1,3,6,9,5,2,4,10)
print(sorted(numbers,reverse=True))
# the output will be in the list

# Set
# Set is an unordered collection of data value
# Set does not allow us to have duplicate values
# Set is denoted by using {} / set()

set1 = {10,20,30,40}
print(type(set1))

set2 = set([10,20,30,40])
print(type(set2))

set3 = set()
print(type(set3))

set1 = {10,20,30,40,30,20,10,10}
print(set1)
# not gonna run any duplicate values
# no guarantee what number they will provide first (unordered)

list1 = [10,20,30,10,30,40,50,20,60,70]
# WAP to print the no. of unique values in a List
print('No. Of Unique Elements',len(set(list1)))

list1 = [10,20,30,10,30,40,50,20,60,70]
# WAP to print the no. of unique values in a List

unique_values = []
for item in list1:
    if item not in unique_values:
        unique_values.append(item)

print("Number of unique values:", len(unique_values))

list1 = [10,20,30,10,30,40,50,20,60,70]
# WAP to print the no. of unique values in a List
empty_list = []                                          # empty_list = []
for i in list1:                                          # i --> 10
  if i not in empty_list:                                # whether 10 does not exist in empty_list FALSE
    empty_list.append(i)                                 # empty_list = [10,20,30]

print('No. Of Unique Elements',len(empty_list))
print(empty_list)

!pip install ordered-set

from ordered_set import OrderedSet
list1 = [10,20,30,10,30,40,50,20,60,70]
print(set(list1))
print(OrderedSet(list1))

# remove dupplicate but keep original ordered
letters = OrderedSet('abracadabra')
print(letters)

# lose original order
letters = OrderedSet('abracadabra')
print(set(letters))

# Dictionary
# used to hold the information in a key:value pair format
# denoted by using {} / dict()
# dictionary is mutable

# in dictionary values can be duplicated but keys has to be unique

emp_info = {"id":101,"empname":"John","dept":"IT",
            "sal":5600,"email":"j@gmail.com","city":"Klang",
            "mobno":60132324}
print(type(emp_info))
print(emp_info)

print(emp_info["sal"])
print(emp_info["mobno"])

# get(keyname)
print(emp_info.get("sal"))
print(emp_info.get("mobno"))

# in dict can't use slicing -> You can't use [start:stop] on a dict
# cannot insert zero [0] -> You can't use [0] unless 0 is a key

emp_info = {"id":[101,102,103],
            "name":['John','Alex','Smith'],
            "dept":['IT','HR','FN']}
print(type(emp_info))
print(emp_info)

print(emp_info["name"])
print(emp_info.get("dept"))

print(emp_info["name"][1])

import pandas as pd
data = pd.DataFrame(emp_info)
data

emp_info = {"id":101,"empname":"John","dept":"IT",
            "sal":5600,"email":"j@gmail.com","city":"Klang",
            "mobno":60132324}

print(emp_info)

# add a new key:value pair
# new key value will add at the end
emp_info['citizenship'] = 'Malaysia'
print(emp_info)

# pop)'keyname') used to delete a key:value pair

emp_info.pop('citizenship')
print(emp_info)

# updating value
emp_info['sal'] = 6000
print(emp_info)

# updating key
# updating key will shift to at the very last
# recomended to make change at the original dict
emp_info['empid'] = emp_info.pop('id')
print(emp_info)

emp_info = {"id":101,"empname":"John","dept":"IT",
            "sal":5600,"email":"j@gmail.com","city":"Klang",
            "mobno":60132324}
#print the keys only - normal for loop
for i in emp_info:
  print(i)

#print the values
for i in emp_info.values():
  print(i)

# print key value together
for k,v in emp_info.items():
  print(k,v,sep=':')

# NESTED LIST COMPREHENSION
# create a new list showing the square of metioned numbers

numbers = [2,3,4,5,6,7,8,9,10]
sq_nums = []
for i in numbers:
  sq_nums.append(i**2)
  print(sq_nums)
# inside loop

numbers = [2,3,4,5,6,7,8,9,10]
sq_nums = []
for i in numbers:
  sq_nums.append(i**2)
print(sq_nums)

numbers = [2,3,4,5,6,7,8,9,10]
sq_nums = [i**2 for i in numbers]
print(sq_nums)

numbers = [10,45,56,67,89,34,99]
# create a new list showing numbers greater than 55
empty_list = []
for i in numbers:
  if i>55:
    empty_list.append(i)
print(empty_list)

numbers = [10,45,56,67,89,34,99]
empty_list = [i for i in numbers if i>55]
print(empty_list)

list1 = [10,20,30,10,30,40,50,20,60,70]
# WAP to print the no. of unique values in a List
empty_list = []
for i in list1:
  if i not in empty_list:   # check the unique value
    empty_list.append(i)    # add only if its not already in the list
print(empty_list)

list1 = [10,20,30,10,30,40,50,20,60,70]
empty_list = []
[empty_list.append(i) for i in list1 if i not in empty_list]
print(empty_list)

normal_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
even_squares = [i ** 2 for i in normal_list if i % 2 == 0]    # Expression for loop if condition
print(even_squares)

nums = [1,2,3,4,5,6,7,8,9]
sq_even =[]
for i in nums:
  if i%2==0:                  # even no. [2,4,6,8]
    sq_even.append(i**2)      # 2**2,4**4,6**6,8**8
print(sq_even)

nums = [1,2,3,4,5,6,7,8,9]
sq_even =[i**2 for i in nums if i%2==0]
print(sq_even)

# Prints:
# "Weird" if the number is odd.

# "Weird" if the number is even and in the range 6 to 20 (inclusive).

# "Not Weird" if the number is even and in the range 2 to 5 (inclusive).

# "Not Weird" if the number is even and greater than 20.

n = int(input("Enter a number: "))

if n % 2 == 1:
    print("Weird")
elif n % 2 == 0 and 2 <= n <= 5:
    print("Not Weird")
elif n % 2 == 0 and 6 <= n <= 20:
    print("Weird")
elif n % 2 == 0 and n > 20:
    print("Not Weird")

# other option
try:
    n = int(input("Enter a number: "))

    if n % 2 == 1:
        print("Weird")
    elif 2 <= n <= 5:
        print("Not Weird")
    elif 6 <= n <= 20:
        print("Weird")
    else:  # n > 20
        print("Not Weird")

except KeyboardInterrupt:
    print("\nInput was interrupted.")
except ValueError:
    print("Please enter a valid integer.")

