# -*- coding: utf-8 -*-
"""Day1-3_YPB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hu6okjU-TMJreHnMtAZlHlI0dS_ljW0f
"""

# COMMENTS
# COMMENTS PROVIDES MEANINGFUL INFORMATION ABOUT YOUR CODE / PROGRAM
# COMMENTS IN PYTHON STARTS WITH #

# print()
# built-in function used to display message or result on a screen
print("Hello World")
print('Welcome To Python')
print ('10+5')

a = 67
b = 3
print("Hello World")
print('Welcome to python')
print(a+b)

# to know more about any built in function
# help(functionName)
help(print)

# sep used to separate value by using a whitespace
print('Python','Programming','Is','Fun','To','Learn')
print(78,89,101)
print('Python','Programming','Is','Fun','To','Learn',sep='-->')

# end used to add \n [newline] at the end of the value
print('Python')              # Python\n
print('Programming')         # Programming\n
print('Nexperts',end='\t')   # \t tabSpace   Nexperts   Academy
print('Academy')             # Academy\n
print('Yash')

# Variables
# a variable is a container for storing the information

# Rules For Variables
# Rule 1 : a variable can not starts with a number
# Rule 2 : a variable can not have a whitespace
# Rule 3 : variables are case sensitive
# Rule 4 : try to avoid using reserved keywords as your variable names
#                   if print help for while def del

# Day 2
# Data Types
# Strings In Python
# Raw Strings
# Character Escape Sequence
# Strings in Triple Quotes
# Indexing And Slicing
# String Formatting

# Data Types
# data type defines what kind of a value a variable can hold

# Python is a Dynamically Typed Programming Language
#   a.) we don't need to write data type before declaring a variable
#   b.) we can re-assign diff diff values to a variable

# INT : used to hold a numeric value [positive / negative]

a = 18
print(a)

# type(varname) : used to determine the data type of a variable

print(type(a))

# FLOAT : used to hold a decimal value
b = 90.231
print(b,type(b))

# STRING : used to hold textual data
c = "Python"
print(c,type(c))

# BOOLEAN : used to hold either True / False
d = True
print(d,type(d))

a = 78
print(type(a))

a = 'Seventy Eight'
print(type(a))

# Strings In Python
# Raw Strings
# Character Escape Sequence
# Strings in Triple Quotes
# Indexing And Slicing
# String Formatting

# String is a data type used to store textual data
# String is a collection of characters
# String can be defined using ' "

str1 = 'Python'
str2 = "Programming"
print(type(str1) , type(str2))

# String is a collection of characters
str1 = 'Python is fun to learn'
# P  y  t   h   o   n     i   s
# 0  1  2   3   4   5  6  7   8  [index numbers --> always starts with a ZERO]
print(str1)
print(str1[3])
print(str1[6])

str1 = 'fiyda'
str2 = 'programming'
print(type(str1), type(str2))

# Indexing
# indexing allows us to retrieve only one single value
# indexing is denoted by using [] square brackets

name = 'fiyda'
# f  i   y    d    a
# 0  1   2    3    4  [forward/positive index numbers]
# -5 -4 -3   -2   -1  [backward/negative index numbers]

print(name)
print(name[0])
print(name[2])
print(name[-4])

# Slicing
# slicing allows to retrieve portion / sub-portion of a sequence
# syntax :   varname[startIndex:stopIndex]
# startIndex : index no. from where slicing will begin     INCLUSIVE
# stopIndex  : index no. where slicing will end            EXCLUSIVE

course = "PythonProgramming"
# P  y   t    h    o     n     P    r    o    g    r    a    m    m    i    n    g
# 0  1   2    3    4     5     6    7    8    9   10    11   12   13   14   15   16

print(course)
print(course[6:13])

# PythonPro course[0:9]
# gram      course[9:13]
#onPro      course[4:9]

print(course[0:9])
print(course[9:13])
print(course[4:9])

# in slicing if stopIndex is missing then slicicing will go through till the last character
# Programming
print(course[6:])

# in slicing if startIndex is missing then slicing will begin from index no. ZERO
print(course[:9])

# syntax :   varname[startIndex:stopIndex:stepCount/interval]
print(course[6:13:2])   # Program   --> P  o  r  m
print(course[6:13:4])   # Program   --> P r

name ="fiyda osman"
# WAP to print string in a reverse order
print(name[::-1])

# Raw Strings
print(r'C:\newFolder\test\abc.txt')

# Character Escape Sequence
print('I didn\'t do that')
print("Welcome To \"Nexperts\" Academy")

print('Welcome To "Nexperts" Academy. It\'s Awesome')

# Strings in triple quotes
print('''Weather Report

      Kuala Lumpur : 27 Degree
      New Delhi    : 32 Degree
''')

# String Concatenation / Formatting
name = "John"
course = "Python"
fees = 1500
# John is learning Python and the fees is 1500RM.
# + operator requires left hand and right hand side value to be of type STRING
print(name+' is learning '+course+' and the fees is '+str(fees)+'RM.')
print(name,'is learning',course,'and the fees is',fees,'RM.')

# in string formatting --> variables are defined in curly braces
print(f'{name} is learning {course} and the fees is {fees} RM.')

name = "Alex"
qty = 2
item = "T-shirt"
price = 299

# Alex wants to purchase 2 T-shirt worth RM299 each.

print(f'{name} wants to purchaes {qty} {item} worth {price} RM each😆')

# DAY 3
# Type Casting
# Taking an user input
# Operators

# Type casting is a process of converting one data type into another data type

# intValue ---> string
# str(intValue)
age = 19
print(age,type(age))

age = str(age)
print(age,type(age))

# floatValue ---> string
# str(floatValue)
result = 90.3333334444
int(result)


# intValue --> float     90 ---> 90.0
# float(intValue)

# floatValue --> int
# int(floatValue)

# boolValue --> string     True --> 'True'
# str(boolValue)

# string --> boolvalue    'True' / 'False' --> True / False

# mistakes to avoid
#name = "yash"            # not possible to turn into int
#print(int(name))

# Taking an user input
# input() built-in function used to take user input
# input(prompt/message)
# age = 90 --> need to take from user

name = input('Enter Your Name : ')
print('Welcome User :',name)

print('Enter Your Email Address')
email = input()  # can left it empty only if the proper print function is provided
print('Your Email Address Is :',email)

# input() function treat every input as a STRING
# need to used type casting for value
val1 = int(input('Enter First Value : '))       # 20
val2 = int(input('Enter Second Value : '))      # 30
res = val1 + val2                               # 20+30
print('After Addition :',res)

# Exercise

name = input('Name : ')
age = int(input('Age : '))
# age=age+1
print('Hi ',name,'Next Year You will be ',age+1,'year old')
print(f'Hi {name}, Next Year you will be {age+1} year old')

# Operators
# Operators are used to perform operations on variables

# Arithmetic Operators
# +  -   *    /   //    %  **

a = 90
b = 5

print(a+b)
print(a-b)
print(a*b)
print(a/b)  # In Python Division Operator Returns Value In FLOAT
print(a//b) # // Floor Division Operator Returns Value In INT
print(a%b)  # gives us remainder
print(a**b) # a raise to the power of b  [90 raise to the power of 5]
print(78**78)

# point to be remember
# in python we don't have increment or decrement operator
a = 100
a = a + 1
print(a)

# a++   a--   not supported in python

import math  # concept of modules packages
print(math.ceil(4.9))
print(math.floor(4.9))

# Assignment Operator  =
a = 90
print(a)

# Compound assignment operator
val = 100
val -= 1      # val = val - 1
print(val)

# Comparison Operator
# <  >   <=   >=   ==   !=
# Returns Value In Boolean [True / False]

print(90<100)
print(100>300)
print(800==800)

age = 17
print(age>=18)  #  age>18  age==18

print(90!=100)

# Logical Operators
# AND OR NOT

# AND operator requires more than one condition
# AND operator returns TRUE only when both the conditions are TRUE

print(100==100 and 50<100)
#      cond1        cond2
#       true         true


print(100==100 and 50>100)
#      cond1        cond2
#       true         false

print(10==100 and 50>100)
#      cond1        cond2
#      false        false

# OR operator requires more than one condition
# OR operator returns TRUE when both the conditions are TRUE
# OR operator returns TRUE if any one of the conditions is TRUE
# OR operator returns FALSE when both the conditions are FALSE

print(100==100 or 50<100)
#      cond1        cond2
#       true         true


print(100==100 or 50>100)
#      cond1        cond2
#       true        false

print(10==100 or 50>100)
#      cond1        cond2
#      false        false

# NOT operator
# inverse the result
# True --> False     False --> True

print(not(100==100 and 50<100))
print(not(100==100 and 50>100))

# Membership Operator
# in  not in

name = "John Smith"
print('o' in name)
print('Smith' in name)
print('s' in name)    # case sensitive

# not in
print('J' not in name)  # 'J' does not exist in name  false
print('s' not in name)  # 's' does not exist in name  true
print('o','m' in name)