# -*- coding: utf-8 -*-
"""DecisionMaking_Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jLcNhiZpAbPWZxCKo6XzNpOmPYRd4lk
"""

# Python Decision Making And Loops
# Working with conditions , Conditional Statements

# if
# if else
# if elif else
# for
# while
# break and continue

# if statement
# if will check the condition first , if the condition is TRUE
# if allows us to execute a block of code

# syntax
# if condn:
#   block of code

age = int(input('Tell me your age : '))
if age>=18:
  print('Awesome! You are eligible for a Driving License')

num = int(input('Enter Any Number : '))
if num%2==0:
  print('Checking The Number')
  print('Number is EVEN')
  print('Still I am in IF')
print('Rest Of The Code')

# Assignment 1 : WAP to print the largest number among 5 variables
a = 19
b = 35
c = 27
d = 141
e = 69

largest = 0

if a>largest:             #  19>0 (t)
  largest = a             # largest = 19

if b>largest:             #  35>19 (t)
  largest = b             # largest = 35

if c>largest:             #  27>35 (f)
  largest = c

if d>largest:             #  141>35 (t)
  largest = d             # largest = 141

if e>largest:             #  69>141 (f)
  largest = e

print(f'Largest is {largest}')

# if else statement   # else cannot write any condn
age = 12
if age>=18:
  print('Welcome User!')
  print('Game Is Loading.....')
  print('Let\'s Play The Game')
else:
  print('Sorry! Age Restriction. You are not eligible for this game')

num = int(input('Enter Any Number : '))
if num%2==0:
  print('Number is EVEN')
else:
  print('Number is ODD')

# if elif else
# only one block of code will be executed at a time
# can use more than 1 elif

num = int(input('Enter Any Number : '))
if num<0:
  print('Negative Number')    # if first condn is false then python will read second condn --- > elif condn
elif num==0:
  print('Number Is Zero')
else:
  print('Positive Number')

# If not used elif python will read line by line

marks = int(input('Enter Marks : '))
if marks<=100 and marks >=85:
  print('A Grade')
elif marks<=84 and marks >=70:
  print('B Grade')
elif marks<=69 and marks >=55:
  print('C Grade')
elif marks<=54 and marks >=40:
  print('D Grade')
elif marks<=39 and marks >=0:
  print('Fail')
else:
  print('Invalid Marks Entered')

# Loops
# Loops are used to perform a repititive task
# For and While

# For Loop
# used to iterate over a sequence
# syntax   for iterable_variable in Sequence:
#              block of code

# AFTER EVERY ITERATION BODY OF FOR LOOP WILL BE EXECUTED

for i in "Python":
  print(i)

product_prices = 25 , 27 , 30 , 32 , 35 , 37 , 40 , 43 , 45 , 46 , 50 , 52 , 53 , 56 , 57 , 61 , 62 , 65 , 67 , 70 , 72
tax = 0.45

# final price list after adding tax
for i in product_prices: # i --> 25
  print(i+tax)           # 25 + 0.45

numbers = 25 , 27 , 30 , 32 , 35 , 37 , 40 , 43 , 45 , 46 , 50 , 52 , 53 , 56 , 57 , 61 , 62 , 65 , 67 , 70 , 72
# using for loop --> print only Even Numbers

# for
# if

for i in numbers:
  if i % 2 ==0:    # 30%2==0 (yes)
    print(i)       # 30

# range() function
# it is used to generate a sequence of Integer Numbers

# a.) range(x)
# it is used to generate a sequence of Integer Numbers
# starting from Zero till x-1

print(list(range(11)))

# b.) range(x,y)
# it is used to generate a sequence of Integer Numbers
# starting from Zero till y-1

print(list(range(1,11)))

# c.) range(x,y,stepCount)
# it is used to generate a sequence of Integer Numbers
# starting from Zero till y-1 based on stepCount

print(list(range(1,11,2)))

# WAP to print all even numbers till 100

print(list(range(2,101,2)))

# WAP to print your name 10 Times
for i in range(1,11):    # 1 2 3 4 5 6 7 8 9 10
  print(f'{i} Nexperts')

try:
    num = int(input('Enter Any Number : '))
    for i in range(1, 15):
        print(f'{num} x {i} = {num*i}')
except KeyboardInterrupt:
    print("\nProcess interrupted by the user.")

num = int(13)
for i in range (1,11):
  print(f"{num} x {i} = {num*i}")

# Nested For Loop
for i in 'red','blue','green':
  for j in 'bus','car','bike':
    print(i,j)

# while loop
# syntax   while condition:
#              block of code
#              incr / decr

i = 1              #  i --> 1
while i<=3:        # 1st Iteration   1<=3     2nd Iteration  2<=3     3rd Iter  3<=3(t)      4th Iter 4<=3(f)
  print(i)         #  1                           2                       3
  i=i+1           # i --> 2                   i --> 3                  i --> 4    i+=1     i=i+1

# 13x1 = 13
# 13x2 = 26
# 13x3 = 39
# ...
# ...
# 13x10 = 130


i = 1
num = 13
while i<=10:
  print(f'{num}x{i} = {num*i}')
  i += 1

# Avoiding Infinite Loop
i = 1                       # i = 1
while i<=3:                 # 1<=3 (t)     1<=3 (t)   1<=3 (t)  1<=3 (t)  1<=3 (t)  1<=3 (t)
  print(i)                  # 1

# USE WHILE LOOP WHEN NUMBER OF ITERATIONS ARE NOT FIXED
howManySubjects = int(input('Enter How Many Subjects Marks You Wish To Insert : '))
i = 1
while i<=howManySubjects:
  marks = int(input(f'Enter Marks For Subject {i} : '))
  i += 1

# try to understand the working of this code
num = int(input("Enter a number: "))

# Store original number
original_num = num

# Reverse the number using while loop
reversed_num = 0
while num > 0:
    digit = num % 10
    reversed_num = reversed_num * 10 + digit
    num = num // 10

# Check if original and reversed are the same
if original_num == reversed_num:
    print("Palindrome")
else:
    print("Not a palindrome")

# break and continue in Loops

# break statement
# used to terminate the execution of a Loop in between
# break should be used inside decision making


for i in "Python":
  if i=='h':
    break
  print(i)

while True:
  q = input('Ask A Query : ')
  if q=='stop' or q=='exit':
    break

# continue to skip the current iteration of Loop
# For each iteration:

# 1st iteration: i = 'P', no match → prints 'P'.

# 2nd iteration: i = 'y', no match → prints 'y'.

# 3rd iteration: i = 't', no match → prints 't'.

# 4th iteration: i = 'h', matches → skips printing.

# 5th iteration: i = 'o', no match → prints 'o'.

# 6th iteration: i = 'n', matches → skips printing.

for i in "Python":
  if i=='h' or i=='n':
    continue
  print(i)

# Guess A Number Game
# Objective : Our machine will generate one random number
# we have to guess that number within 4 attempts

import random
attempt = 0
max_attempt = 4

name = input('Tell Me Your Name : ')
print('Welcome User :',name,'\nGame Is Loading. Please Wait.....')
print('Our Machine Is Generating One Random Number B/W 1 till 15')
num = random.randint(1,15)
print('\nNumber Is Generated. Guess The Number In 4 Attempts')

while attempt < max_attempt:
  guess_num = int(input('Enter Your Number : '))
  attempt += 1

  if guess_num < num:
    print('Your Guess Is Too Low. Think Of A Higher Number')

  if guess_num > num:
    print('Your Guess Is Too High. Think Of A Lower Number')

  if guess_num == num:
    print(f'Congratulations! You Won The Game In {attempt} attempts')
    break

if guess_num!=num:
  print(f'Sorry! {attempt} attempts left. You Lost The Game. The Number Was {num}')

# Note
# Variable Assignment: --> attempt = 0   max_attempt = 4
# input() Function:  --> name = input('Tell Me Your Name : ')
# print() Function: --> print('Welcome User :', name, '\nGame Is Loading. Please Wait.....')
#                   --> print('Our Machine Is Generating One Random Number B/W 1 till 15')
# random.randint(): --> num = random.randint(1, 15) --> generates a random integer between 1 and 15
# while Loop: --> while attempt < max_attempt: --> A while loop runs the code inside it repeatedly as long as the condition (attempt < max_attempt) is True
# input() with int(): --> guess_num = int(input('Enter Your Number : '))
# Incrementing Variables: --> attempt += 1
# if Statements: --> if guess_num < num:  if guess_num == num:
# break Statement: --> break --> The break statement exits the loop early, so the game stops if the player guesses the number correctly.
# f-string for String Formatting: --> print(f'Congratulations! You Won The Game In {attempt} attempts') --> The f-string (formatted string literal) is used to embed variables (attempt in this case) directly inside the string.
# if Statement for Checking Game Loss: --> if guess_num != num: --> After the loop ends, this if checks if the player did not guess correctly (if guess_num is not equal to num), and if true, it prints the game over message.

# Summary of Syntax Used:
# Syntax	Purpose
# attempt = 0	Variable assignment
# input()	Take user input as a string
# print()	Display output to the user
# random.randint()	Generate a random number between a range
# while loop	Repeat code based on a condition
# int()	Convert string input to integer
# attempt += 1	Increment the attempt variable by 1
# if statement	Conditional checks (for low/high/ correct guesses)
# break	Exit the loop early
# f-string	String formatting with embedded variables