# -*- coding: utf-8 -*-
"""Exception_Handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRUNojblP2oIdLvx6X6YVRWKFWOUHfFi
"""

# Exception handling in Python is a mechanism that allows you to handle runtime errors,
#  or exceptions, in a controlled way, rather than letting your program crash unexpectedly.
# Python provides a way to catch errors, respond to them, and allow your program to continue
# running smoothly even if something goes wrong.

# try except finally
# try : keep the block inside try , which might give you an error
# except : catch that error

# Without Exception Handling

val1 = int(input('Enter First Value :'))
val2 = int(input('Enter Second Value :'))
res = val1 / val2
print('After Division :',res)
print('Rest Of The Code')

# With Exception Handling

try:
  val1 = int(input('Enter First Value :'))
  val2 = int(input('Enter Second Value :'))
  res = val1 / val2
  print('After Division :',res)
except:
  print('Something Went wrong')
print('Rest Of The Code')

try:
  val1 = int(input('Enter First Value :'))
  val2 = int(input('Enter Second Value :'))
  res = val1 / val2
  print('After Division :',res)
except Exception as e:
  print('Error :',e)
print('Rest Of The Code')

try:
  val1 = int(input('Enter First Value :'))
  val2 = int(input('Enter Second Value :'))
  res = val1 / val2
  print('After Division :',res)
except ZeroDivisionError as e:         # use only when you know what the error is
  print('Error :',e)
print('Rest Of The Code')

# define multiple exceptions
# but only one exception will work at a same time

try:
  val1 = int(input('Enter First Value :'))
  val2 = int(input('Enter Second Value :'))
  res = val1 / val2
  print('After Division :',res)
except (ZeroDivisionError,ValueError) as e:
  print('Error :',e)
print('Rest Of The Code')

# finally keyword
# it will execute  always

# Case 1 : when there is no exception

try:
  val1 = int(input('Enter First Value :'))
  val2 = int(input('Enter Second Value :'))
  res = val1 / val2
  print('After Division :',res)
except Exception as e:
  print('Error :',e)
finally:
  print('I will execute always')
print('Rest Of The Code')

# Case 2 : when there is an exception

try:
  val1 = int(input('Enter First Value : '))
  val2 = int(input('Enter Second Value : '))
  res = val1 / val2
  print('After Division :',res)
except Exception as e:
  print('Error :',e)
finally:
  print('I will execute always')
print('Rest Of The Code')

# Case 3 : when there is an exception but not handled properly

try:
  val1 = int(input('Enter First Value :'))
  val2 = int(input('Enter Second Value :'))
  res = val1 / val2
  print('After Division :',res)
except ModuleNotFoundError as e:
  print('Error :',e)
finally:
  print('I will execute always')
print('Rest Of The Code')