# -*- coding: utf-8 -*-
"""OOPs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kzh1LwetemjAI24PfibAa0PtcTA0TyG_
"""

# OOPS
# OOP stands for Object-Oriented Programming.
# Object-oriented programming (OOP) is a programming paradigm based on the
# concept of "objects"

# Procedural programming is about writing procedures or methods that perform operations
# on the data, while object-oriented programming is about creating objects
# that contain both data and methods.

# Object-oriented programming has several advantages over procedural programming:

# a.) OOP is faster and easier to execute
# b.) OOP provides a clear structure for the programs
# c.) OOP helps to keep the Java/Python code DRY "Don't Repeat Yourself", and makes the code easier
#     to maintain, modify and debug
# d.) OOP makes it possible to create full reusable applications with less code and
#     shorter development time

# Class
# A class is a blueprint that defines the variables and the methods common to all objects.
# a class is a collection of methods and variables


# Object
# An object is called an instance of a class.


# Self Keyword
# The self parameter is a reference to the current instance of the class, and is used to
# access variables that belongs to the class.
# The first parameter of each method in a class must be the self ,
# which refers to the calling object. However, you can give any name to the first
# parameter, not necessarily self.

# __init__ in Python
#  Constructors are used to initializing the object’s state. The task of constructors is
# to initialize(assign values) to the data members of the class when
# an object of the class is created.
# The __init__() function is called automatically every time the class is being used to create
# a new object.

# A class is a collection of variable and methods
# in python we define class using 'class' keyword

class myclass:

  ''' This is my first class in python programming oops'''

  a = 10
  b = 20

  def func1():
    print('Hi I am a class function')

  def func2():
    print('Hi I am another class function')   # at this point if you run nothing gonna show up because you just create a class

help(myclass)

class myclass:

  a = 10           # member variables
  b = 20

  def func1():     # member methods
    print('Hi I am a class function')

  def func2():
    print('Hi I am another class function')

print(myclass.a)    # not suggested to use
myclass.func1()
print(myclass.b)
myclass.func2()

# in order to access class variable or methods
# create the object of a class

class myclass:

  ''' This is my first class in python programming oops'''

  a = 10
  b = 20

  def func1():
    print('Hi I am a class function')

  def func2():
    print('Hi I am another class function')

# creating An Object
# A class can have n number of objects
obj1 = myclass()
obj2 = myclass()


print(obj1.a)
print(obj2.a)

# use self keyword
# first parameter of a class function should be SELF

# self represent the current calling instance (object)

class myclass:

  a = 10
  b = 20

  def func1(fiyda):                      # func1(obj1)   func1(obj2) --> who want to use the function at the moment
    print('Hi I am a class function')

  def func2(self):
    print('Hi I am another class function')


obj1 = myclass()
obj2 = myclass()


print(obj1.a)
print(obj2.a)

obj2.func2()
obj1.func2()

'''When you use loops, lists, dictionaries, and functions (but not classes/objects)

→ you are following the Procedural Programming approach


You organize code into procedures (functions) and use control structures like loops (for, while), conditionals (if, else), and data structures (list, dict, etc.) to handle data.
'''

# WAP to take 3 details from 3 users

# Taking details for user1
print("Enter details for User 1:")
user1_name = input("Name: ")
user1_email = input("Email: ")
user1_mobno = input("Mobile No: ")

# Taking details for user2
print("\nEnter details for User 2:")
user2_name = input("Name: ")
user2_email = input("Email: ")
user2_mobno = input("Mobile No: ")

# Taking details for user3
print("\nEnter details for User 3:")
user3_name = input("Name: ")
user3_email = input("Email: ")
user3_mobno = input("Mobile No: ")

# a) Print all information
print("\n--- All Users Information ---")
print("User1:", user1_name, user1_email, user1_mobno)
print("User2:", user2_name, user2_email, user2_mobno)
print("User3:", user3_name, user3_email, user3_mobno)

# b) Print information for 2nd user
print("\n--- Information for 2nd User ---")
print("Name:", user2_name)
print("Email:", user2_email)
print("Mobile No:", user2_mobno)

# c) Print mobile number of 3rd user
print("\n--- Mobile number of 3rd User ---")
print("Mobile No:", user3_mobno)

# WAP to take 3 details (name, email, mobno) from 3 users using loops and lists

users = []  # list to store all users' details

# Taking details of 3 users
for i in range(3):
    print(f"\nEnter details for User {i+1}:")
    name = input("Name: ")
    email = input("Email: ")
    mobno = input("Mobile No: ")

    # store one user's info as a list inside the main list
    users.append([name, email, mobno])

# a) Print all information
print("\n--- All Users Information ---")
for i, user in enumerate(users, start=1):
    print(f"User{i}: Name = {user[0]}, Email = {user[1]}, Mobile No = {user[2]}")

# b) Print information for 2nd user
print("\n--- Information for 2nd User ---")
print(f"Name: {users[1][0]}")
print(f"Email: {users[1][1]}")
print(f"Mobile No: {users[1][2]}")

# c) Print mobile number of 3rd user
print("\n--- Mobile number of 3rd User ---")
print(f"Mobile No: {users[2][2]}")

# WAP TO TAKE 2 DETAILS FROM 3 USERS

# user1
# name =
# email =
# mobno =

# user2
# name =
# email =
# mobno =

# a. print all information
# b. print the information for 2nd user
# c. print the mobno of 3rd user


users = {}


for i in range(1, 4):
    print(f"\nEnter details for user {i}:")
    name = input("  Name: ")
    email = input("  Email: ")
    mobno = input("  Mobile No: ")


    users[f"user{i}"] = {
        "name": name,
        "email": email,
        "mobno": mobno}


print("\nMenu:")
print("a. Print all information")
print("b. Print information for 2nd user")
print("c. Print the mobile number of 3rd user")

choice = input("Enter your choice (a/b/c): ").strip().lower()


if choice == 'a':
    print("\nAll Users' Information:")
    for key, info in users.items():
        print(f"\n{key}:")
        print(f"  Name: {info['name']}")
        print(f"  Email: {info['email']}")
        print(f"  Mobile No: {info['mobno']}")

elif choice == 'b':
    u2 = users.get("user2")
    if u2:
        print("\nInformation of 2nd User:")
        print(f"  Name: {u2['name']}")
        print(f"  Email: {u2['email']}")
        print(f"  Mobile No: {u2['mobno']}")
    else:
        print("User 2 not found.")

elif choice == 'c':
    u3 = users.get("user3")
    if u3:
        print(f"\nMobile number of 3rd user: {u3['mobno']}")
    else:
        print("User 3 not found.")

else:
    print("Invalid choice.")

# to store user info
users = []

# loop for 3 users
for i in range(3):
    print(f"\nEnter details for user {i+1}:")
    name = input("Enter name: ")
    email = input("Enter email: ")
    mobile = input("Enter mobile number: ")

    # store each user's data in a dictionary
    user_info = {
        "Name": name,
        "Email": email,
        "Mobile": mobile
    }

    # add to the users list
    users.append(user_info)

# display all users
print("\nUser Details:")
for user in users:
    print(user)

# display user number 2 info
print("\nUser 2 Details:", users[1])

# display mobile number for user 3 only
print("\nUser 3 Details:")
print("Mobile:", users[2]["Mobile"])

class takeUserDetails:

  def __init__(self,n,e,mn):     # __init__(c1,n,e,mn)           __init__(c2,n,e,mn)
    self.name = n                # c1.name = "John"               c2.name = "Alex"
    self.email = e               # c1.email = "j@gmail.com"       c2.email = "al@gmail.com"
    self.mobno = mn              # c1.mobno = 603564543           c2.mobno = 601424232

  def printDetails(self):                             # printDetails(c1)
    print(self.name,self.email,self.mobno)            # c1.name  c1.email  c1.mobno

c1 = takeUserDetails("John","j@gmail.com",603564543)
c2 = takeUserDetails("Alex","al@gmail.com",601424232)
c3 = takeUserDetails("Tina","tn@gmail.com",646362721)

# Printing all information
print('---- Information Of All Users ----')
c1.printDetails()
c2.printDetails()
c3.printDetails()

# Print the second user information
print('\n\n---- Information Of Second User----')
c2.printDetails()

# Print the mobno of 3rd user
print('\n\n---- Third User Mob No----')
print(c3.mobno)