# -*- coding: utf-8 -*-
"""Python_API's.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168SPD_rpEcYhFwGZTGMTPIhg1g7-gjAu
"""

# What is an API?
# API stands for Application Programming Interface.

# Think of it like a waiter in a restaurant:
# You (the user) tell the waiter what you want (e.g., a burger).
# The waiter takes your request to the kitchen (the system).
# The kitchen prepares the food and gives it to the waiter.
# The waiter brings it back to you.

# In tech terms:
# You (the app or user) send a request using the API.
# The API talks to a server or system.
# The system sends back the data.
# You get the result in your app.

'''
Benefits of Using APIs

Saves Time
You don’t need to build everything from scratch. Use APIs to access services others already built.

Enables Integration
APIs let different apps or systems "talk" to each other. For example, your weather app gets data from a weather API.

Real-time Access
APIs let apps fetch live or updated data instantly (like traffic updates or prices).

Secure and Controlled
APIs allow access to data without exposing everything—you only get what the provider allows.

Scalable and Flexible
You can add more features easily by using more APIs.
'''

'''
Examples
1. Grab (Ride-hailing & Delivery App)

Grab uses many APIs to function. For example:

Google Maps API – to show maps, routes, and real-time traffic.

Payment APIs – for cashless payments.

Notification APIs – to send messages to your phone about your driver or order.

Location APIs – to find where you are and where to go.


Example: When you book a Grab ride:

The app uses location APIs to detect your pickup point.

Then it uses Google Maps API to calculate distance and route.

It might use pricing APIs to calculate your fare.

Finally, it uses notification APIs to update you when your ride is near.
'''

# "APIs are like pre-written functions or services provided by other software or companies,
# available over the internet, that you can use in your own apps."

# An API is a bridge that connects two different software systems so
# they can talk to each other and share information.

# Wolframalpha API
!pip install wolframalpha==3.0.0

import wolframalpha

app_id = "5JQEQE3YTY"  # Replace this with your actual App ID
client = wolframalpha.Client(app_id)

res = client.query('temperature in kuala lumpur')
res

query = input('Question : ')
res = client.query(query)
if res['@success']=='true':
    pod0=res['pod'][0]['subpod']['plaintext']
    print(pod0)
    pod1=res['pod'][1]
    if (('definition' in pod1['@title'].lower()) or ('result' in  pod1['@title'].lower()) or (pod1.get('@primary','false') == 'true')):
        result = pod1['subpod']['plaintext']
        print(result)
else:
    print("No answer returned")

query = input('Question : ')
res = client.query(query)
if res['@success']=='true':
    pod0=res['pod'][0]['subpod']['plaintext']
    print(pod0)
    pod1=res['pod'][1]
    if (('definition' in pod1['@title'].lower()) or ('result' in  pod1['@title'].lower()) or (pod1.get('@primary','false') == 'true')):
        result = pod1['subpod']['plaintext']
        print(result)
else:
    print("No answer returned")

import wolframalpha

# Replace with your Wolfram Alpha App ID
APP_ID = "5JQEQE3YTY"

# Initialize the client
client = wolframalpha.Client(APP_ID)

def query_wolfram(query):
    try:
        res = client.query(query)
        answer = next(res.results).text
        return answer
    except StopIteration:
        return "No results found."
    except Exception as e:
        return f"Error: {e}"

def main():
    print("Welcome to the Smart Knowledge Assistant!")
    print("Ask me anything (type 'exit' to quit).")
    while True:
        user_input = input("\nYou: ")
        if user_input.lower() in ['exit', 'quit']:
            print("Goodbye!")
            break
        response = query_wolfram(user_input)
        print(f"Answer: {response}")


main()